const allAnimalsData = [
  {
    id: 0,
    name: "Rocky",
    type: "Dog",
    breed: "Terrier Mix",
    age: 12,
    imgs: ["./img/rockygrizzled.jpg"],
    shortDesc: "Rocky is a friendly, well behaved pup and the perfect companion for long walks!",
    longDesc: "",
    houseTrained: true,
    energy: 1,
    affection: 1,
    obedience: 2,
    specialNeeds: 0,
    children: 2,
    strangers: 2,
    otherAnimals: 2
  },
  {
    id: 1,
    name: "Scout",
    type: "Dog",
    breed: "Terrier Mix",
    age: 3,
    imgs: ["./img/scoutportrait.jpg"],
    shortDesc: "Scout is a spunky terrier who loves nothing more than taking a nap on your lap!",
    longDesc: "",
    houseTrained: true,
    energy: 2,
    affection: 2,
    obedience: 1,
    specialNeeds: 0,
    children: 1,
    strangers: 2,
    otherAnimals: 2
  },
  {
    id: 2,
    name: "Teddy",
    type: "Dog",
    breed: "Terrier Mix",
    age: 5,
    imgs: ["./img/teddy.jpg"],
    shortDesc: "Teddy loves to play fetch and jam to his <a href=\"https://www.youtube.com/watch?v=ci_pCk0l-WA\">favorite song</a>!",
    longDesc: "",
    houseTrained: true,
    energy: 2,
    affection: 2,
    obedience: 2,
    specialNeeds: 0,
    children: 2,
    strangers: 1,
    otherAnimals: 2
  },
  {
    id: 3,
    name: "Badger",
    type: "Dog",
    breed: "Cool Guy",
    age: 6,
    imgs: ["./img/badger.jpg"],
    shortDesc: "When he's not making funny faces, Badger can most often be found curled up under a pile of blankets.",
    longDesc: "",
    houseTrained: true,
    energy: 1,
    affection: 2,
    obedience: 1,
    specialNeeds: 0,
    children: 2,
    strangers: 2,
    otherAnimals: 2
  },
  {
    id: 4,
    name: "Hedgy",
    type: "Hedgehog",
    breed: "Four-Toed Hedgehog",
    age: 2,
    imgs: ["./img/hedgy.jpg"],
    shortDesc: "Don't let his spikey exterior fool you — Hedgy the Hedgehog is full of love!",
    longDesc: "",
    houseTrained: false,
    energy: 1,
    affection: 0,
    obedience: 0,
    specialNeeds: 0,
    children: 0,
    strangers: 2,
    otherAnimals: 0
  },
  {
    id: 5,
    name: "Emily",
    type: "Dog",
    breed: "Formosan Mountain Dog",
    age: 3,
    imgs: ["./img/emily.jpg"],
    shortDesc: "Emily is wary of new people, but give her a few treats, and she'll warm up to you!",
    longDesc: "",
    houseTrained: true,
    energy: 2,
    affection: 1,
    obedience: 1,
    specialNeeds: 0,
    children: 0,
    strangers: 0,
    otherAnimals: 1
  },
];

module.exports = allAnimalsData;